// ─────────────────────────────────────────────────────────────
//  AVALANCH-E — POSTS
//
//  To add a new post: copy one of the blocks below, edit it,
//  and paste it at the top of the POSTS array (order doesn't
//  matter — the site sorts by dateSort automatically).
//
//  Fields:
//    id        — unique URL slug, lowercase, hyphens only
//    dateSort  — 'YYYY-MM-DD' (controls sort order, always use this format)
//    dateLabel — how the date is displayed, e.g. 'March 14, 2026'
//    title     — post title
//    excerpt   — one-line summary shown on the home page
//    paragraphs— array of strings, one per paragraph
//
//  To edit an existing post, just change the text in place.
//  To delete a post, delete its whole { ... } block.
//
//  Straight quotes (') inside text must be escaped like this: \'
//  Regular double quotes (") inside text are fine as-is.
// ─────────────────────────────────────────────────────────────

const POSTS = [
  { id: 'cool-memories-i', dateSort: '2026-03-14', dateLabel: 'March 14, 2026',
    title: 'Cool Memories I',
    excerpt: 'Fragments on simulation, seduction, and the death of the real.',
    paragraphs: [
      'The obscenity of our age is not that everything is hidden, but that everything is exposed — the pornography of total visibility, where even the secret has been made to perform its secrecy for an audience.',
      'We were promised liberation and were given transparency instead, which is a much crueler thing. A secret can be kept. A performance of having nothing to hide can never rest.',
      'Truth has not been suppressed; it has been multiplied past the point of use, like a currency printed until it buys nothing. Hyperinflation of the fact.',
      'Seduction is the only intelligence left to us. Explanation is for those who have already lost.',
      'The map preceded the territory a long time ago. What we now mistake for reality is the territory\'s attempt to resemble its own map, badly, and gratefully.'
    ]
  },
  { id: 'on-authenticity', dateSort: '2026-01-03', dateLabel: 'January 3, 2026',
    title: 'Against Authenticity',
    excerpt: 'The self that must announce itself as real has already lost the argument.',
    paragraphs: [
      'Authenticity is the last mask that claims not to be one. Every other mask admits its status; this one insists it is the face.',
      'To be told "just be yourself" is to receive an order disguised as a permission. Try refusing it and discover how little permission was actually on offer.',
      'The confessional mode — the diary, the personal essay, the deathbed sincerity performed at thirty — is not the opposite of performance. It is performance that has learned to despise its own name.',
      'I trust the liar who knows he is lying more than the sincere man who has simply automated his sincerity. At least the liar is still awake.'
    ]
  },
  { id: 'on-the-death-of-god-and-other-good-news', dateSort: '2025-11-02', dateLabel: 'November 2, 2025',
    title: 'On the Death of God, and Other Good News',
    excerpt: 'We did not kill him. We simply stopped needing an alibi.',
    paragraphs: [
      'God did not die of an argument. No god ever has. He died of irrelevance, which is a much slower and more humiliating death than the one philosophy likes to stage for him.',
      'What frightens the moralist is not that god is dead but that his absence changed nothing on Tuesday morning. The bakery opened. The trains ran late. Meaning did not evacuate the premises — it simply stopped waiting for a landlord.',
      'Those who mourn the death of god are usually mourning the death of an excuse: the excuse not to have invented their own values, their own severities, their own reasons to rise before noon.',
      'I do not ask you to become an atheist. I ask you to notice how much work the word "sin" was doing for you, and whether you are willing to do that work yourself now.'
    ]
  },
  { id: 'on-cruelty-as-a-form-of-honesty', dateSort: '2025-07-19', dateLabel: 'July 19, 2025',
    title: 'On Cruelty as a Form of Honesty',
    excerpt: 'Kindness is often just cowardice with better public relations.',
    paragraphs: [
      'Every ethics of niceness is secretly an ethics of avoidance: better to withhold the true sentence than risk the discomfort of having said it.',
      'I do not recommend cruelty. I recommend noticing how much of what passes for kindness is simply the fear of consequence wearing a gentler word.',
      'The cruelest man I ever met told the truth so plainly that people mistook his honesty for malice, because they had never encountered the former unaccompanied by flattery and assumed it must be the latter.',
      'A compliment costs nothing and is therefore worth exactly that. Save your praise for what has actually earned the risk of your disapproval.'
    ]
  },
  { id: 'notes-on-boredom-as-revolt', dateSort: '2025-04-08', dateLabel: 'April 8, 2025',
    title: 'Notes on Boredom as Revolt',
    excerpt: 'The bored man is the last person the algorithm cannot reach.',
    paragraphs: [
      'Boredom used to be a private failure. Now it is nearly an act of resistance — the one remaining state the feed cannot monetize, because it produces no click, no scroll, no data worth harvesting.',
      'To be entertained continuously is to be governed continuously. The tyrant\'s oldest trick was bread and circuses; ours does not even require the bread.',
      'I have come to suspect my own restlessness. Each time I reach for the device out of boredom, I am not fleeing an empty moment — I am fleeing the only moment in which I might have noticed something true about my life.',
      'Cultivate boredom the way a monk cultivates silence. It is not empty. It is simply not for sale yet.'
    ]
  },
  { id: 'aphorisms-against-the-thesis', dateSort: '2025-01-22', dateLabel: 'January 22, 2025',
    title: 'Aphorisms Against the Thesis',
    excerpt: 'A short defense of the fragment over the argument.',
    paragraphs: [
      'An argument tries to survive its critics. An aphorism does not care whether it survives — it has already said the thing and left the room.',
      'The academic paper is a coffin built slowly, with footnotes for nails. I would rather leave a wound than a monument.',
      'Systems are for those afraid of being caught contradicting themselves. I contradict myself constantly. It is the only sign I am still thinking rather than reciting.',
      'A truth that requires forty pages to defend was probably not true enough to begin with. Say the sharp thing. Let the reader do the forty pages, if they must.',
      'I do not build. I quarry. Let the masons come later, if they dare, and if the stone lets them.'
    ]
    },
  { id: '2025-shitpost-supercut', dateSort: '2025-12-30', dateLabel: 'December 30, 2025',
    title: '2025 Shitpost Supercut',
    excerpt: 'A short defense of the fragment over the argument.',
    paragraphs: [
      'Identity politics circling the toilet bowl',
      '',
      'Instead of the Lynchian dark underbelly of a community, imagine an equal parts destitute and evil surface only to reveal a utopian underground of benevolence. ',
      '',
      'The problem with continuing a thought or sentence is the inevitability of the retroactivity. Everything that comes after a thought or series of words devours what comes before it. For example, an indifferent moon is recontextualized when juxtaposed with empty streets late at night versus a sweet grass that carries the melodies of myriad insects. ',
      '',
      'W(h)ither Liberalism',
      '',
      'Universe, please do me a solid',
      '',
      'Ride the John Stuhr train',
      '',
      'It doesn’t matter whether or not I’m the first one to say it. What matters is that it is said, even if it is said over and over again.',
      '',
      'You think your life is euphoria but you should curb your enthusiasm. It’s always sunny with friends, especially when you’re the new girl, but your severance package is at the office ',
      '',
      'Are you counting sheep or clapping cheeks?',
      '',
      'It literally costs nothing to stop beating myself up',
      '',
      'Things have to get worse before they get worse',
      '',
      'Constant self loathing is a form of narcissism ',
      '',
      'If language is what separates us from animals, why don’t we teach young people how to read well, write well, and speak well?',
      '',
      'The time of bodies in space rhetoric has come to an end. We don’t need a small army of Judith Butler misinterpreters. Let’s think our own thoughts instead of sitting in the house of intellectual celebrities. ',
      '',
      'Rather than extract information, we need sit with, to sit in each thing ',
      '',
      'Two birds land on the string lights / The string lights sway lazily as the birds move laterally while perched like typewriters / The birds bob and bounce with no precarity / An orange leaf spirals downward in the foreground envious of its animal cousins',
      '',
      'I look out the window while I’m waiting on my bread to toast. Three white tailed deer in the backyard. Then five. Then six. Grazing and strolling. A herding dog sprints to the edge of its fence and barks. The deer run back to the tree line.',
      '',
      '“Help! Artificial Intelligence is Eating My brain!”',
      '',
      'Increasingly tortured readings of reality ',
      '',
      'Artificial general intelligence is pure instrumentality without thought. This is the opposite of what our society is lacking. What we desperately need is pure thought without instrumentality. ',
      '',
      'Oedipus / Episcopal / Oedipuscipal',
      '',
      'Starving kids in my city while millionaires live in mansions. How could anyone say that’s fine. Why haven’t we stopped everything we are doing to fix this. To redistribute the wealth and take care of each other. ',
      '',
      'I promise I’m not a linguistic idealist, but I feel myself smack headfirst into language constantly.',
      '',
      'Ego pulls the trigger ',
      '',
      'Despite being educated and culturated by institutions, I do not respect any institution for its own sake. Institutions inscribed my body with signifiers to make me legible to other institutions, but I reject their language. I reject their interpretation of who I am and what I am. I even reject my own interpretation of who and what I am. All I can say in my immediacy is that I am. Not knowing what “that” is, not knowing what “I” is, the only thing left to say is — Am. ',
      '',
      'Renegotiated my experience of time',
      '',
      'Slow news day…over the last 2,000 years ',
      '',
      'Conservatives have no sense of imagination',
      '',
      'People won’t know how you feel until you tell them.',
      '',
      'Space and time have become too compressed ',
      '',
      'If you’re anything like me, you spend way too much time living in your mind and not enough time living in your body. ',
      '',
      'Plumb the depths of your soul / See what waters spring forth',
      '',
      'Strength: ideation machine. Weakness: implementation machine. ',
      '',
      'Communication is only made possible by non-communication. ',
      '',
      'It’d be easier to love my enemies if they weren’t so fucking stupid.',
      '',
      'Billboards may be the ugliest thing to have ever existed',
      '',
      'Too much is never enough',
      '',
      'To others: Be friendly. Be gentle. Be firm. ',
      '',
      'For many people it is easier to imagine economic prosperity than political prosperity. Political prosperity is a more appropriate evaluative framework than merely thinking of rights. Rights feel crystalline, when in reality the integrity, breadth, and depth of those rights ebbs and flows with regime changes, events, policies. Rights need to be exercised in order to be maintained, otherwise people will not be able to realize when they are gone. Similarly, crystalline rights as laws are too often consigned to oblivion via arcane language and archival concealment and obscurantism. That one would need to become a scholar to understand the machinations of the law and legal system are not a testament to the robustness of the law but rather its failure to be a tool for the public good. ',
      '',
      'We need to live lives where our data and metadata have no value. We need to live decommodified lives. ',
      '',
      'Do you think items are sold to help you or to make money? The answer to this question illuminates much.',
      '',
      'One fear I have is that people will misconstrue my thoughts and see them as intentionally obscurantist. It sucks to know how that most Americans on average are at an 8th grade reading level. Even more are an a 6th grade reading level. So when I discuss chirality in Kantian metaphysics and epistemology I may as well be speaking gobbledygook. ',
      '',
      'The aesthetic field is not grounds or means for a revolution, let alone a meaningful change. ',
      '',
      'One cannot experience another as a subject. One can only experience another as an object.',
      '',
      'There is no enlightened terrain.',
      '',
      'The history of leaving me alone',
      '',
      'My tax dollars go to drone strikes but they can’t go to helping my fellow man? Despicable. I spew you from my mouth.',
      '',
      'I am Tony Soprano',
      '',
      'Everyone in my generation has overdosed on self awareness ',
      '',
      'If electoralism worked, the will of the people would have been properly expressed ages ago. ',
      '',
      'The question remains, would you give an extra 10% of everything you have to ensure that everyone in your community has what they need? If you were skeptical or hesitated or had secondary questions about the “how,” then you are part of the problem. Because I didn’t ask “could it be done?” I asked “would you?” It’s clear where your heart and head are at. ',
      '',
      'Philip Oliver Holes',
      '',
      'My message is short. It isn’t urgent because it is already too late. We must move from anti capitalism to postcapitalism. That is the only way we have a chance of living a life that isn’t saturated in pure misery.',
      '',
      'I refuse to merely toil and then perish. I will make something worthwhile that outlasts me. Even though that too will eventually perish. ',
      '',
      'God reared his ugly head and in a slimey whisper said “this is good”',
      '',
      'Short story idea: daily silent protestor on Capitol Hill deteriorating and rotting ',
      '',
      'You don’t have to be smart to realize that someone who thinks themselves to be smart is actually stupid. ',
      '',
      'Carpool tunnel',
      '',
      'The liberal desire for self actualization is exhausting, and the conservative desire to throw everyone they don’t like into the meat grinder is also exhausting. ',
      '',
      'I don’t know if Derrida could have anticipated the entire American English lexicon being reduced to Buffy Speak',
      '',
      'A book as a suicide note doesn’t work because the act of suicide cannibalizes the work of the deceased. The death itself is retroactively inscribed upon the work, making the content of the work slave to the suicide itself.',
      '',
      'David Lynch once said that Einstein must have felt frustrated about being surrounded by idiots. Lynch’s own genius held a weight of a different kind. Was he burdened by his own excellence relative to his peers?',
      '',
      'Fuck abundance, just give me what I need ',
      '',
      'The strange part is, I just want everyone to feel my suffering. And I want to feel theirs. So finally we can break bread and eat eep [sic] and say “finally, we understand each other!”',
      '',
      'Waiting for the validation of others was my biggest mistake',
      '',
      'We need more Greg Grandins and Eugene McCarrahers and Norman Finkelsteins',
      '',
      'I just wanna enroll in the Salamanca school ',
      '',
      'My entire generation of poets has been ruined by free verse. ',
      '',
      'Terminologically and theoretically inarticulate',
      '',
      'Baron Trump comes in there — With a steel chair!',
      '',
      'Oh no it’s daddy gumbo',
      '',
      'Grinding rails, sniffing lines louder than cocaine snausages'
      ]
     },
  { id: '2024-shitpost-supercut', dateSort: '2024-12-30', dateLabel: 'December 30, 2024',
    title: '2024 Shitpost Supercut',
    excerpt: 'A short defense of the fragment over the argument.',
    paragraphs: [
      'Just let me live and die this stupid suburban life. Let me act like /pretend I live outside of history, live outside of time. In a sea of houses with no sidewalks. Ebbing sams clubs flowing costcos. Seasons pass like scrapbooks and themed parties. Toothpaste on sale and crock pots of plastic cheese recipes buffalo chicken dip.',
      '',
      'Kick flip and blow up the spot / Leaving planet earth with all that Ive got / Sun bound that shit gets too hot / Cold shoulder thought you cool but you not',
      '',
      'My life is best defined as a check engine light',
      '',
      'I am the one through whom pain flows',
      '',
      'IDEa: paranormal horror about UN Refugee ambassador / humanitarian crises policy writer / political anthropologist / academic. Think Darfour. Think Myanmar. ',
      '',
      'Your obedience to the system is prolonging our suffering ',
      '',
      'What I wish for my brothers and sisters is peace love and good fortune',
      '',
      'The more you learn the bigger the world gets / Everyone dies four times / Death of the mind / Death of the body / Death of everyone who knew you / Death of any trace of your existence',
      '',
      'Blame artists so desperate to “innovate” and staple shitty conceptual apparatuses to their work for it to be appraised as “deep” and “thought provoking.” This idea is was created and destroyed once Duchamp perfected it with “The Fountain”',
      '',
      'Custer’s last joint ',
      '',
      'Nothing quite sneaks up on you like time',
      '',
      'There are only two political parties: the oppressors and the oppressed',
      '',
      'I don’t care about what you believe in. I care about how you treat others',
      '',
      'The epistemological jungle: pure excess of knowledge and guidelines for bushwhacking. ',
      '',
      'I know why you lose but it’s something I could never do',
      '',
      'Poets manipulate words because they are dissatisfied with their reality',
      '',
      'I want to be like Arnaut Daniel but I’m just Alfred Prufrock',
      '',
      'Was Plato worried about his resume when he was sold into slavery? Was Epictetus concerned with his legacy when his leg was being broken?',
      '',
      'With every breath, we share this world.',
      '',
      'A chorus of decay and nothing more',
      '',
      'How sad is it that people may reject me for the shape of my face or the shape of my body rather than the shape of my soul',
      '',
      'If we consider two types of knowledge, knowledge by acquaintance and knowledge by description, we run into a problem. Determining whether or not some else’s knowledge is by acquaintance or description becomes next to impossible. After all, how can one truly prove that they know something? ',
      '',
      'Idea: hey chat gpt - “how to reverse taxidermization” - we must revive this capybara!',
      '',
      'Rocks are indifferent to their own configuration, properties, and process of formation ',
      '',
      'All a photo does is hide something',
      '',
      'Perhaps the most charitable take on Fukuyama’s ‘end of history’ is the fact that most individuals (in America, at least) have ceased to understand themselves as historical subjects.',
      '',
      'Just as the most savory foods turn to feces and the most delicious wines turn to urine, so too will the problems that seem overwhelming in their intensity and reality come to pass and be excreted from you as waste.',
      '',
      'Joyful warrior / Swift of feet / Dance in blood / Clencing teeth / Wild grin / Lightning strikes / Feel the rain / Black as night / Ride the clouds / Harvest souls / X / X',
      '',
      'Description is prescription ',
      '',
      'Sometimes thinking about soul crushing stuff gets tiring ',
      '',
      'God asking Abraham to kill Isaac must have been a test run for when Jesus came along.',
      '',
      'Every knee will bow / And every tongue confess/ That we are absolutely fucked',
      '',
      'We are commanded to enjoy things. This imprisons us.',
      '',
      'Metaphor is a prison because it prevents us from understanding things on their own terms ',
      '',
      'I want to create a song that sounds like a caveman or proto human lying down to go to sleep during the day inside a cave with damp hair and a gentle beam of light passing through a slightly overcast and drizzling sky. Someone is concerned that he will get a cold if he falls asleep with his hair wet (an old wives tale), but the dichotomy of nature and civilization, health and unhealth, bare life and culture, falls away and all that remains is sensation.',
      '',
      'You are trapped by your own physical appearance. How much of your life is determined by what you look like and how others respond to it. What sadness. What a sad condition we find ourselves in. Fuck aesthetics.',
      '',
      'Every author, consciously or otherwise, presents a metaphysics in their written works.',
      '',
      'Long is the night where one lies awake in the dark',
      '',
      'Information deserts',
      '',
      'Do you help those in need? Do you play the roles that life has given to you well? Are you a loyal and virtuous parent, child, sibling, friend, citizen, coworker, student, mentor, teacher? Do you back away from the blessings and challenges that are afforded to you in this brief life? Or do you embrace them as they come without judgement? Do you show fidelity to the truths that unfold before you? Do you bear witness to life itself and affirm it in all its aspects?',
      '',
      'Why not simply call a hyper-object a complex object? Timothy Morton explain!',
      '',
      'Leopold’s Land Ethic is just a “noble savage”ing of space and place',
      '',
      'why are the Chandrian just the Nazgûl but different?',
      '',
      'The global village was condemned due to code violations'
    ]
  },
  { id: 'on-the-obscenity-of-optimization', dateSort: '2023-12-30', dateLabel: 'December 30, 2023',
    title: '2023 Shitpost Supercut',
    excerpt: 'The self as a spreadsheet is the final joke played on the soul.',
    paragraphs: [
      'My suffering is pavement',
      ' ',
      'If you knew what I know you’d feel the same.',
      ' ',
      'Mainstream American journalists are scum',
      ' ',
      'People line up to have their souls eaten by Mickey Mouse',
      ' ',
      'The next liberal to ask for nuance gets kicked in the urethra',
      ' ',
      'I lit the St. Jude candle for health even though I treat my body like shit',
      ' ',
      'The cruel indifference of the sun and moon',
      ' ',
      'The human face is the ultimate site of dissimulation. Filled with such useless information that we are unfortunately repelled or drawn in by the mere whims of gene expression. ',
      ' ',
      'Have you ever held someone’s hand as they were breathing their last breaths? Have you ever walked with someone from life to death? ',
      ' ',
      'I used to think you were just a brat only concerned with yourself. Now I’ve realized you’re much worse. You’re the worst thing anyone in this world can be. You’re a fucking coward. ',
      ' ',
      'All my knowledge is second hand. I don’t know anything.',
      ' ',
      'We used to conquer danger. Today, humans conquer frustration.',
      ' ',
      'Walk Away Slowly.',
      ' ',
      ' *in a southern drawl* - to their white surprise',
      ' ',
      'How sad is it that peoples social interactions can be influenced by the aesthetic evaluation of one’s own face',
      ' ',
      'We never escape our bodies in the same way we never escape the social. We are trapped, confined within. To be outside the social would be akin to being outside the body. But even when we don’t experience our body (during states such as sleep), those experiences are only made possible by the ground of possibility the body provides. The experience of the non-experience of our bodies is only possible because of our bodies.',
      ' ',
      'Never trust a Rawlesian',
      ' ',
      'Decolonization itself has been commodified',
      ' ',
      'Challenging meta narratives is healthy, but this does not mean that we should outright reject all of them. Imagine the danger of rejecting observations regarding colonialism and racial global empire.',
      ' ',
      'Academics speak of their own conception of the working class with an impoverished and mistaken notion of what the working class actually is. ',
      ' ',
      'What is it like to fall endlessly?',
      ' ',
      ' She is beauty she is grace she will punch you in the face',
      ' ',
      'I’ll just keep living my stupid American life',
      ' ',
      'I don’t want to ever go to Harvard if they were dumb enough to let Ted Cruz in.',
      ' ',
      'Death is standing by your body drinking coffee and making phone calls',
      ' ',
      'The things most people think of as good are actually evil.',
      ' ',
      'Go ahead, push the sword through my mouth',
      ' ',
      'Eat the rich. Grind them up in your fucking teeth and spit out their blood. Crush them into powder and blow them away into the wind. Stomp them out of existence. The world ends thanks to their complicity.',
      ' ',
      'You can kill me, but you can’t kill an idea',
      ' ',
      'Movie idea: genre: horror/comedy. Someone is being terrorized/haunted by a paranormal entity, ghost, demon, vampire, etc. but no one around this person cares because they are more concerned with their own endeavors. Imagine a scene where the person being terrorized confides in  one of their friends of acquaintances and the friend says “wow that really sucks but I have to keep working on providing malaria nets for children in Africa.” “You shouldn’t be so self centered, a lot of people have much worse situations in the world.” Imagine another scene where our protagonist seeks help from another friend but that friend is too busy teaching inner city kids musical theatre to help said kids process and overcome their trauma. Friend says something obnoxious like “you know these kids I work with have their own skeletons in the closet, their own demons they have to exorcise, their own ghosts that haunt them.” Protagonist and the spirit that haunts them have a conversation about how the difficulties of finding someone to commiserate with or assist them is worse than the actual haunting going on at this point, so the spirit just leaves because it can’t even compete with that. ',
      ' ',
      'The world has turned me into a big baby',
      ' ',
      'Seinfeld is passed gas from the bloated corpse of world spirit.',
      ' ',
      'Plastics arts are not a means of social progress or revolution. They will always be trapped in curatorial bourgeois places for shitlibs to feel politically activated for 0.5 seconds before throwing the working class back into the meat grinder to sustain their comfortable lifestyle.',
      ' ',
      ' The white cisgender heterosexual able bodied male alliance for the queer indigenous differently abled immigrant/new American decolonial people of color coalition for equitable equality ',
      ' ',
      'I don’t mind the cold. Unless I do. Then I do. ',
      ' ',
      'Another casualty- my asshole and butt cheeks. The coarse translucent toilet paper paired with a messy shit strikes again as I wipe my backside into oblivion. Fucking bullshit. No ass deserves the pain of wiping primitive toilet paper across their rear ad Infinitum to no avail. Bidets. Wet wipes. Healing salves. A soft caress of a fabric or biomass friendlier than the indifferent countenance of a death cult roll. The white demon tortures me at every corner. Poseidon, relinquish me from this misery. May your watery jets christen my nether regions and protect me from the tyranny of the ever present snowy tapestry of doom.',
      ' ',
      'True love doesn’t exist. True love must exist.',
      ' ',
      'If anyone asks, I died typing stupid notes into my phone',
      ' ',
      'Identity is not interesting. How do you act? What do you say? What do you think? What are your dreams? How will you spend your time on this little planet? Will you spend it whining? Will you walk circles in your head and retread the same tired thoughts and feelings handed to you from the outside? Or will you break the mold? Will you overcome? Will you laugh at those who doubted you and leave your detractors in the dust? Will you retreat and find those you know will console you with uninteresting platitudes? Are you predictable?',
      ' ',
      'Mental illness is not an abnormality but the logical conclusion given one’s environment.',
      ' ',
      'Much of what has been written under the banner of philosophy deserves to be thrown into the trash.',
      ' ',
      'Most slam poetry sucks. Emotion doesn’t equal quality craft.',
      ' ',
      'It appears we would rather be butchered (quickly or slowly) by the world that already exists than dare to work toward creating a new one.',
    ]
  },
  { id: '2022-shitpost-supercut', dateSort: '2022-12-30', dateLabel: 'December 30, 2022',
    title: '2022 Shitpost Supercut',
    excerpt: 'Memory is not a virtue. It is a habit we have failed to interrogate.',
    paragraphs: [
      'The next person who says they’re busy gets kicked in the urethra.',
      ' ',
      'Communities exist to do what cannot be done alone.',
      ' ',
      'We need porcupine scented candles.',
      ' ',
      'We run around getting our ass continually fucked by the posthuman entity that is capitalism and the only lube we have is shitty media.',
      ' ',
      'A fate worse than death: being greedy selfish or stupid.',
      ' ',
      'Sometimes we keep our heads in our asses because that feels like the safest place to put it.',
      ' ',
      'Ladies and germs, there will be no cthulhucene.',
      ' ',
      'If people could commune with the dead, they’d probably only hear one thing: “Fuck you.”.',
      ' ',
      'Just as Heidegger mistook Van Gogh’s shoes for those of a peasant woman, I wonder what I overlook in such a profound but hilarious way..',
      ' ',
      'As soon as you think you’re too good to learn from someone your education has ended.',
      ' ',
      'Life is the excrement of death :: Death is the excrement of life.',
      ' ',
      'Poverty is a wound. Wealth is a disease.',
      ' ',
      'If you have one foot in the past and one in the future you will end up pissing on today.',
      ' ',
      'I’ve spent a third of my life trying to figure out what the fuck is going on.',
      ' ',
      'Every fear conjured about totalitarian states has already been realized by private corporations',
      ' ',
      'Every element of contemporary life feels like an abject failure which rests upon the bodies of lost figures and abandoned dreams and compromises.',
      ' ',
      'Learning to love myself is one of the hardest things I’ve ever done.',
      ' ',
      'Any city that does not take care of its poor is an abject failure.',
      ' ',
      'Common sense is an enemy to philosophy because common sense is merely ideology without a subject.',
      ' ',
      'Is the right to(ward) self determination the ultimate right? What are the limits of self determination, especially in a shared space? In a world of limited configurations of material, are there not things one may aspire to do that are impossible? What are the limits of self determination?',
      ' ',
      'When one is willing to examine and potentially relinquish every thought, idea, belief, and conviction, that is when true philosophy occurs.',
      ' ',
      'Intersectionality is no longer interesting.',
      ' ',
      'I will write to express myself, not to be understood. Those who will understand me will understand me.',
      ' ',
      'People are their most dangerous when they have stopped learning.',
      ' ',
      'If we could speak, the dead would never understand us.',
      ' ',
      'Once I finally get off the couch it’s over for you mfs.',
      ' ',
      '‘Human rights’ is an elusive term for many reasons. Access to the internet was originally a scientific rarity, then a privilege, then a ubiquitous tool, and the internet has become so entangled in life that navigating many facets of the world without it seems grossly inconvenient. Applying for a job, submitting legal documents, etc. is now almost entirely dependent on the internet. So lack of access to the hybrid material and immaterial entity has social, political, and emotional repercussions. To what extent must a lack of access to something constitute a harm in order to generate discussions of rights to it? The right to internet access appears normative. But perhaps there is something underneath this plea. Perhaps there is a form, with internet as it’s content, that gives one an innate desire to pose an argument in the realm of rights. Others having a lack which can potentially mar their social, emotional, mental, physical, political, ideological health raises concerns. However, one could look at the abundance of maladies people face and argue that the addition of any entity with ameliorative potential makes it worthy of right-hood.',
      ' ',
      'People are worthy of having all of their needs and wants met given that they can do so in a healthy way.',
    ]
  }
];
